# display single-line
add_newline = false
[line_break]
disabled = true

# nerd-font preset: copy/paste this from the page linked below

[aws]
symbol = " "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
symbol = " "

[cmake]
format="via [$symbol$version]($style)"

[dart]
symbol = " "

[directory]
#read_only_symbol = "⚿"
read_only_symbol_style = "blue"

[docker]
symbol = " "

[dotnet]
disabled = true

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[git_status]
disabled = true

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "
